export const productos = [
  {
    id: 1,
    nombre: "Lakers Jersey",
    category: 'Jerseys',
    img: 'https://fanatics.frgimages.com/los-angeles-lakers/mens-nike-lebron-james-gold-los-angeles-lakers-2020/21-swingman-jersey-icon-edition_pi3774000_altimages_ff_3774124-8dda7d765787e82d6c61alt1_full.jpg?_hv=2&w=900',
    precio: 150,
    stock: 1,
    description: "Men's Los Angeles Lakers LeBron James",
  },
  {
    id: 2,
    nombre: "Grizzlies Jersey",
    category: 'Jerseys',
    img: 'https://images.footballfanatics.com/memphis-grizzlies/unisex-nike-ja-morant-white-memphis-grizzlies-swingman-jersey-association-edition_pi4650000_ff_4650314-fb8c56626e881897a775_full.jpg?_hv=2',
    precio: 100,
    stock: 15,
    description: "Unisex Memphis Grizzlies Ja Morant Nike",
  },
  {
    id: 3,
    nombre: "Hawks Jersey",
    category: 'Jerseys',
    img: 'https://fanatics.frgimages.com/atlanta-hawks/mens-jordan-brand-trae-young-black-atlanta-hawks-authentic-player-jersey-statement-edition_ss5_p-5269568+pv-1+u-qeva6h8os97jdsppigzl+v-tu9rgz3fhchv3jynzl24.jpg?_hv=2&w=900',
    precio: 100,
    stock: 6,
    description: "Men's Atlanta Hawks Trae Young Fanatics Branded Black",
  },
  {
    id: 4,
    nombre: "Spurs Jersey",
    category: 'Jerseys',
    img: 'https://images.footballfanatics.com/san-antonio-spurs/san-antonio-spurs-nike-icon-swingman-jersey-2023-nba-draft-first-round-pick-black-victor-wembanyama-unisex_ss5_p-200340709+u-voqsjqqzupudg9acihpb+v-7mzyvkv6luqgusjydijn.jpg?_hv=2&w=600',
    precio: 125,
    stock: 19,
    description: "Unisex San Antonio Spurs Victor Wembanyama",
  },
  {
    id: 5,
    nombre: "Mavs Jersey",
    category: 'Jerseys',
    precio: 100,
    img: 'https://fanatics.frgimages.com/dallas-mavericks/mens-nike-luka-doncic-royal-dallas-mavericks-swingman-jersey_pi3231000_ff_3231568-ce1eb6d722d4427b2ea5_full.jpg?_hv=2',
    stock: 17,
    description: "Men's Dallas Mavericks Luka Doncic Jersey",
  },
  {
    id: 6,
    nombre: "Suns Jersey",
    category: 'Jerseys',
    img: 'https://images.footballfanatics.com/phoenix-suns/phoenix-suns-nike-icon-edition-swingman-jersey-purple-kevin-durant-unisex_ss4_p-13348408+u-159wmy9jw4yy2bv8s9w2+v-547f853790f2440d9709f287cbc7e7b5.jpg?_hv=2',
    precio: 130,
    stock: 11,
    description: "Men's Phoenix Suns Kevin Durant Jersey",
  },
  {
    id: 7,
    nombre: "Heat Jersey",
    category: 'Jerseys',
    img: 'https://fanatics.frgimages.com/miami-heat/mens-fanatics-branded-jimmy-butler-white-miami-heat-2023-nba-finals-fast-break-player-jersey-association-edition_ss5_p-200209442+u-rtn6wlnk1ccemdcjkasi+v-ez9ji9ishtm0hqodt3yj.jpg?_hv=2',
    precio: 110,
    stock: 10,
    description: "Unisex Miami Heat Jimmy Butler Finals",
  },
  {
    id: 8,
    nombre: "GSW Jersey",
    category: 'Jerseys',
    img: 'https://images.footballfanatics.com/golden-state-warriors/golden-state-warriors-nike-icon-swingman-jersey-stephen-curry-mens_ss4_p-12020130+u-97u8ef14qporv8j3yhs5+v-6ecb720cd9c343d99ff8bf037a21c8e7.jpg?_hv=2',
    precio: 135,
    stock: 9,
    description: "Men's Golden State Warriors Stephen Curry",
  },
  {
    id: 9,
    nombre: "LAL Short",
    category: 'Shorts',
    img: 'https://fanatics.frgimages.com/los-angeles-lakers/mens-jordan-brand-purple-2019/20-los-angeles-lakers-icon-edition-swingman-shorts_pi3763000_altimages_ff_3763986-d7b4d2d76491268bbf86alt1_full.jpg?_hv=2&w=900',
    precio: 80,
    stock: 12,
    description: "Men's Los Angeles Lakers Jordan Brand Purple 2019/20 Icon Edition Swingman Shorts's Golden State Warriors Stephen Curry",
  },
  {
    id: 10,
    nombre: "GSW Short",
    category: 'Shorts',
    img: 'https://fanatics.frgimages.com/golden-state-warriors/mens-nike-black-golden-state-warriors-2022/23-city-edition-swingman-shorts_pi4753000_altimages_ff_4753697-12869999dd4b2795a655alt1_full.jpg?_hv=2&w=900',
    precio: 70,
    stock: 6,
    description: "Men's Golden State Warriors Nike Black 2022/23 City Edition Swingman Shorts",
  },
  {
    id: 11,
    nombre: "Bulls Short",
    category: 'Shorts',
    img: 'https://fanatics.frgimages.com/chicago-bulls/mens-jordan-brand-black-2019/20-chicago-bulls-icon-edition-swingman-shorts_pi3763000_altimages_ff_3763968-031c94362706182da8daalt1_full.jpg?_hv=2&w=900',
    precio: 80,
    stock: 1,
    description: "Men's Chicago Bulls Jordan Brand Black 2019/20 Icon Edition Swingman Shorts",
  },
  {
    id: 12,
    nombre: "Grizzlies Short",
    category: 'Shorts',
    img: 'https://fanatics.frgimages.com/memphis-grizzlies/mens-nike-white-2019/20-memphis-grizzlies-icon-edition-swingman-shorts_ss5_p-3763915+pv-1+u-hbzhkxs9dj5tlymq6ppf+v-1pvctz8yoj2pzveoxt60.jpg?_hv=2&w=900',
    precio: 80,
    stock: 5,
    description: "Men's Memphis Grizzlies Nike White 2019/20 Icon Edition Swingman Shorts",
  },
  {
    id: 13,
    nombre: "Heat Short",
    category: 'Shorts',
    img: 'https://fanatics.frgimages.com/miami-heat/mens-nike-black-2019/20-miami-heat-icon-edition-swingman-shorts_pi3004000_altimages_ff_3004695alt1_full.jpg?_hv=2&w=900',
    precio: 135,
    stock: 16,
    description: "Men's Miami Heat Nike Black 2019/20 Icon Edition Swingman Shorts",
  },
  {
    id: 14,
    nombre: "Celtics Hoodie",
    category: 'Hoodies',
    img: 'https://fanatics.frgimages.com/boston-celtics/mens-jordan-brand-black-boston-celtics-courtside-statement-edition-pullover-hoodie_ss5_p-5267907+pv-1+u-bxtlf9ogyv97bvfovwpx+v-s3t1fgiwnjybltiahpxy.jpg?_hv=2&w=900',
    precio: 95,
    stock: 4,
    description: "Men's Boston Celtics Jordan Brand Black Courtside Statement Edition Pullover Hoodie",
  },
  {
    id: 15,
    nombre: "Bulls Hoodie",
    category: 'Hoodies',
    img: 'https://fanatics.frgimages.com/chicago-bulls/mens-mitchell-and-ness-red-chicago-bulls-hardwood-classics-legendary-slub-pullover-hoodie_ss5_p-200490799+pv-1+u-dbwxge1chqtqobbfvbmv+v-ncsxkrx0vh3nbggqi3de.jpg?_hv=2&w=900',
    precio: 75,
    stock: 7,
    description: "Men's Chicago Bulls Mitchell & Ness Red Hardwood Classics Legendary Slub Pullover Hoodie",
  },
  {
    id: 16,
    nombre: "Cavs Hoodie",
    category: 'Hoodies',
    img: 'https://fanatics.frgimages.com/cleveland-cavaliers/mens-mitchell-and-ness-blue-cleveland-cavaliers-hardwood-classics-legendary-slub-pullover-hoodie_ss5_p-200490800+pv-1+u-lti56mmqqcxv4weoofqf+v-fqpheeugjtoaxqx99tvk.jpg?_hv=2&w=900',
    precio: 75,
    stock: 2,
    description: "Men's Cleveland Cavaliers Mitchell & Ness Blue Hardwood Classics Legendary Slub Pullover Hoodie",
  },
  {
    id: 17,
    nombre: "Knicks Hoodie",
    category: 'Hoodies',
    img: 'https://fanatics.frgimages.com/new-york-knicks/unisex-black-new-york-knicks-suga-x-nba-by-mitchell-and-ness-capsule-collection-glitch-pullover-hoodie_ss5_p-200540265+pv-1+u-nbniohfivqbzo6rvstuk+v-zeluzmkepmngtku21a9w.jpg?_hv=2&w=900',
    precio: 119,
    stock: 7,
    description: "Unisex New York Knicks Black SUGA x NBA by Mitchell & Ness Capsule Collection Glitch Pullover Hoodie",
  },
  {
    id: 18,
    nombre: "Lakers Hoodie",
    category: 'Hoodies',
    img: 'https://fanatics.frgimages.com/los-angeles-lakers/mens-fanatics-branded-black-los-angeles-lakers-2020-nba-finals-champions-team-caricature-fitted-pullover-hoodie_pi4108000_altimages_ff_4108490-fae49e16b71e656595f5alt1_full.jpg?_hv=2&w=900',
    precio: 81,
    stock: 6,
    description: "Men's Los Angeles Lakers Fanatics Branded Black 2020 NBA Finals Champions Team Caricature Fitted Pullover Hoodie",
  },
];
